language: node_js
node_js: stable
branches:
  only:
  - master
  - develop
addons:
  ssh_known_hosts:
  - gz.oidiotlin.com
install:
- npm install
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_bf9f7cd5c89d_key -iv $encrypted_bf9f7cd5c89d_iv
  -in travis.enc -out travis -d
- eval "$(ssh-agent -s)"
- chmod 600 travis
- ssh-add travis
deploy:
- provider: script
  script: rsync -az --delete ./dist/* travis@gz.oidiotlin.com:/var/www/projexor-web/
  on:
    branch: master
