language: node_js
node_js: stable

branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - gz.oidiotlin.com
install:
- npm install
script:
- npm run build
before_install:
- echo $encrypted_bf9f7cd5c89d_key
- openssl aes-256-cbc -K $encrypted_bf9f7cd5c89d_key -iv $encrypted_bf9f7cd5c89d_iv
  -in .travis/travis.enc -out .travis/travis -d
- chmod 600 .travis/travis
- ssh-add .travis/travis
after_success:
- rsync -az --delete ./dist/* travis@gz.oidiotlin.com:/var/www/projexor-web/
